import { readFile } from "node:fs/promises";
import path from "node:path";
import type { Impact } from "@blast/impact";
import { applyUnifiedDiff } from "./applyDiff.js";
import { groupExactImpactsByFile } from "./groupByFile.js";
import { type ExecFileFn, pushAndOpenDraftPr } from "./openDraftPr.js";
import { estimateCostUsd } from "./pricing.js";
import { buildPrompt, buildRetryPrompt } from "./prompt.js";
import { commitAll, createScratchBranch, discardUncommittedChanges } from "./scratchBranch.js";
import type { LlmClient, LlmUsage, PatchAttempt, PatchRequest, PatchRunResult, VerifyResult } from "./types.js";
import { verify as runVerify } from "./verify.js";

const MAX_RETRIES = 2; // total attempts = 1 initial + 2 retries = 3

export interface RunPatchForFileOptions {
  /** The frontend repo (or subdirectory) checkout this file lives in -- also where verification runs. */
  cwd: string;
  /** Absolute path to the file being patched. */
  file: string;
  impacts: Impact[];
  llmClient: LlmClient;
  model: string;
  testCommand?: string;
  storybookBuildCommand?: string;
  relevantTypes?: string;
}

function sumUsage(a: LlmUsage, b: LlmUsage): LlmUsage {
  return { inputTokens: a.inputTokens + b.inputTokens, outputTokens: a.outputTokens + b.outputTokens };
}

/** Runs the send-apply-verify loop for one file, retrying with the verifier's error output on failure, up to MAX_RETRIES times. */
export async function runPatchForFile(options: RunPatchForFileOptions): Promise<PatchRunResult> {
  const start = Date.now();
  const originalContent = await readFile(options.file, "utf8");
  const request: PatchRequest = {
    file: options.file,
    impacts: options.impacts,
    fileContent: originalContent,
    ...(options.relevantTypes ? { relevantTypes: options.relevantTypes } : {}),
  };

  let usage: LlmUsage = { inputTokens: 0, outputTokens: 0 };
  const attempts: PatchAttempt[] = [];
  let lastDiff = "";
  let lastVerify: VerifyResult = { status: "fail", output: "" };

  for (let attempt = 1; attempt <= MAX_RETRIES + 1; attempt++) {
    const prompt = attempt === 1 ? buildPrompt(request) : buildRetryPrompt(request, lastDiff, lastVerify);
    const response = await options.llmClient.requestPatch(prompt);
    usage = sumUsage(usage, response.usage);
    lastDiff = response.diff;

    const applyResult = await applyUnifiedDiff(options.file, response.diff);
    if (!applyResult.applied) {
      lastVerify = { status: "fail", output: "The diff did not apply cleanly to the file (context lines didn't match)." };
      attempts.push({ attempt, diff: response.diff, verify: lastVerify });
      continue;
    }

    lastVerify = await runVerify({
      cwd: options.cwd,
      ...(options.testCommand ? { testCommand: options.testCommand } : {}),
      ...(options.storybookBuildCommand ? { storybookBuildCommand: options.storybookBuildCommand } : {}),
    });
    attempts.push({ attempt, diff: response.diff, verify: lastVerify });

    if (lastVerify.status === "pass") {
      await commitAll(options.cwd, `blast: fix ${path.basename(options.file)} for backend API changes`);
      return { file: options.file, outcome: "verified", attempts, usage, costUsd: estimateCostUsd(options.model, usage), durationMs: Date.now() - start };
    }

    // Restore the known-good base before the next attempt (or before giving up) so a
    // half-applied failed patch never lingers in the working tree.
    await discardUncommittedChanges(options.cwd);
  }

  return { file: options.file, outcome: "needs-human", attempts, usage, costUsd: estimateCostUsd(options.model, usage), durationMs: Date.now() - start };
}

export interface RunPatcherOptions {
  cwd: string;
  /** Full Impact[] from the impact package -- only `exact` ones are patched, per SPEC.md. */
  impacts: Impact[];
  llmClient: LlmClient;
  model?: string;
  testCommand?: string;
  storybookBuildCommand?: string;
  branchName?: string;
  baseBranch?: string;
  /** Must be explicitly opted into -- this pushes a branch and calls `gh pr create`. Default false. */
  openPr?: boolean;
  /** Injectable for tests: asserts the right git/gh commands without really running them. */
  execForPr?: ExecFileFn;
}

export interface RunPatcherResult {
  fileResults: PatchRunResult[];
  branchName: string;
  prUrl?: string;
}

function buildPrBody(results: PatchRunResult[]): string {
  const lines = ["Automated fix for backend API changes, generated by API Blast Radius.", "", "## Files patched"];
  for (const result of results) {
    const attemptWord = result.attempts.length === 1 ? "attempt" : "attempts";
    lines.push(`- \`${result.file}\` (${result.attempts.length} ${attemptWord}, $${result.costUsd.toFixed(4)})`);
  }
  return lines.join("\n");
}

/**
 * Runs the whole patch batch on one scratch branch: groups exact impacts by file, patches
 * each in turn (committing to the scratch branch as each verifies), and opens a draft PR
 * ONLY if every file verified and the caller explicitly opted into `openPr` -- never pushes
 * to `baseBranch`, never auto-merges. See DECISIONS.md for why PR-opening isn't exercised
 * against a real GitHub remote in tests.
 */
export async function runPatcher(options: RunPatcherOptions): Promise<RunPatcherResult> {
  const model = options.model ?? process.env.BLAST_MODEL ?? "claude-sonnet-5";
  const branchName = options.branchName ?? `blast/api-fix-${Date.now()}`;
  const groups = groupExactImpactsByFile(options.impacts);

  await createScratchBranch(options.cwd, branchName);

  const fileResults: PatchRunResult[] = [];
  for (const [file, fileImpacts] of groups) {
    fileResults.push(
      await runPatchForFile({
        cwd: options.cwd,
        file,
        impacts: fileImpacts,
        llmClient: options.llmClient,
        model,
        ...(options.testCommand ? { testCommand: options.testCommand } : {}),
        ...(options.storybookBuildCommand ? { storybookBuildCommand: options.storybookBuildCommand } : {}),
      }),
    );
  }

  const allVerified = fileResults.length > 0 && fileResults.every((result) => result.outcome === "verified");

  let prUrl: string | undefined;
  if (allVerified && options.openPr) {
    prUrl = await pushAndOpenDraftPr(
      {
        cwd: options.cwd,
        branch: branchName,
        baseBranch: options.baseBranch ?? "main",
        title: "blast: fix frontend for backend API changes",
        body: buildPrBody(fileResults),
      },
      options.execForPr,
    );
  }

  return { fileResults, branchName, ...(prUrl ? { prUrl } : {}) };
}
